version: '3'

services:
  proxy:
    depends_on:
      - server
      - phpmyadmin
      - db
    links:
      - server
      - phpmyadmin
    image: nginx:alpine
    volumes:
      - ${PROJECT_HOME}/docker/conf/default/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    logging:
      options:
        max-size: "10k"
        max-file: "3"
